
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::249345434414:role/udacity-final-project-vitor-network-ClusterRole-ECRMMAW96IYQ
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::342863339545:user/capstone
      username: capsotone
      groups:
        - system:masters